win32: Make sure that all addon projects define TARGET_WINDOWS
In the recent PVR API sync, _WIN32 has been replaced by TARGET_WINDOWS.
Since this is a project specific define and not a system variable,
we have to make sure that all PVR addons define this in their project
configuration.

Compilation of addons without TARGET_WINDOWS fails with:
c:\program files (x86)\microsoft visual studio 10.0\vc\include\xxresult(280):
  error C2953: 'std::tr1::_Result_of1<_Rx(__thiscall _Arg0::* )(void),_Farg0&>':
    class template has already been defined
c:\program files (x86)\microsoft visual studio 10.0\vc\include\xxresult(172):
  see declaration of 'std::tr1::_Result_of1<_Rx(__thiscall _Arg0::* )(void),_Farg0&>'